VERSION 0.8

ARG DEFAULT_COMMIT_MESSAGE="[] - Update"
ARG MAIN_BRANCH="main"
ARG GIT_HUGO_REPOSITORY="github.com/myrepo"


PUSH_GIT:
    FUNCTION

    ARG src
    ARG commit=$DEFAULT_COMMIT_MESSAGE
    ARG branch=${MAIN_BRANCH}

    RUN git add ${src}
    RUN git commit --allow-empty -m "${commit}"

    RUN --push --secret GIT_CI_USERNAME \
        --secret GIT_PASSWORD \
        git push https://${GIT_CI_USERNAME}:${GIT_PASSWORD}@${GIT_HUGO_REPOSITORY} HEAD:${branch}
